# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'AEPCommerceDemoApp'
project 'AEPCommerceDemoApp.xcodeproj'

target 'AEPCommerceDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AEPEdge', :path => '../../'
  pod 'AEPCore', '3.2.4'
  pod 'AEPServices', '3.2.4'
  pod 'AEPLifecycle', '3.2.4'
  pod 'AEPIdentity', '3.2.4'
  pod 'AEPSignal', '3.2.4'
  pod 'AEPEdgeIdentity'
  pod 'AEPAssurance'
  pod 'AEPAnalytics', '3.0.1'
end
