theme: jekyll-theme-cayman
title: Adobe Experience Platform Edge Network mobile extension
description: This extension allows you to send data to the Adobe Experience Platform Edge Network from a mobile application. 

