name: PR Opened
run-name: PR Opened
on:
  pull_request:
    types: [opened, reopened, synchronize, assigned, edited, ready_for_review]
    paths-ignore:
      - '.circleci/**'
      - '.githooks/**'
      - '.github/**'
      - 'Documentation/**'
      - 'Script/**'
      - 'Makefile'
      - '*.md'

jobs:
  pr-opened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PR opened with number
        run: |
          echo PR opened: #${{ github.event.number }}
